// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Contact struct {
	ID        int64
	UserID    uuid.UUID
	Name      string
	Email     sql.NullString
	Phone     sql.NullString
	Company   sql.NullString
	Position  sql.NullString
	Notes     sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID                uuid.UUID
	Username          string
	Email             string
	FirstName         string
	LastName          string
	PasswordHash      string
	EmailVerified     bool
	Role              string
	Plan              string
	VerificationToken sql.NullString
	TokenSentAt       sql.NullTime
	StripeCustomerID  sql.NullString
	CreatedAt         time.Time
	UpdatedAt         time.Time
}
