// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID            uuid.UUID
	Username      string
	Email         string
	FirstName     string
	LastName      string
	PasswordHash  string
	EmailVerified bool
	Role          string
	Plan          string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
